apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontoserver-data
  namespace: ontoserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo