apiVersion: v1
kind: ServiceAccount
metadata:
  name: ontoserver
  namespace: ontoserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ontoserver
  name: ontoserver-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ontoserver-rolebinding
  namespace: ontoserver
subjects:
- kind: ServiceAccount
  name: ontoserver
  namespace: ontoserver
roleRef:
  kind: Role
  name: ontoserver-role
  apiGroup: rbac.authorization.k8s.io